-- GENERATED by scripts/backfill-upstream-dispositions.mjs — review before applying.
-- Source ledger: scripts/upstream-dispositions.json (19 entries)
--
-- One literal UPDATE per ledger entry, a generated catch-all for any terminal row
-- closed between generation and deployment (Gemini-round-1 G1 — a time-of-generation-
-- to-time-of-deployment race), then the NOT-NULL-equivalent constraint. All three in
-- this ONE file so setup-postgres.mjs --migrate's normal single-transaction-per-file
-- execution guarantees the constraint never exists without the data that satisfies it.

UPDATE upstream_issues SET disposition = 'exempt:Ordinary config-value tuning (GEMINI_REVIEW_TIMEOUT_MS too tight) — no environment signature a probe could detect, and no dedicated regression test locks the specific timeout value.' WHERE id = '9e6850d3-b910-40d5-b082-d7deeede54c5';
UPDATE upstream_issues SET disposition = 'probe:sync/fresh-clone-contract' WHERE id = 'd902962b-f6ce-4986-8fe4-e86e07d59fa3';
UPDATE upstream_issues SET disposition = 'exempt:Process issue (report filed from the wrong — synced consumer — copy of a source-repo-only e2e test), not a code defect. wont_fix is the correct terminal state; there is nothing here for a probe or a test to close.' WHERE id = 'df083b3a-e06f-4d5f-ba70-7fafbe751c8c';
UPDATE upstream_issues SET disposition = 'exempt:Ordinary code defect (a repo-identity object passed where a uuid was expected in one call site) — no environment signature, and no regression test could be confidently identified as covering this specific fix rather than the surrounding feature generally.' WHERE id = '65f9fe89-e766-4580-8a41-c0390fb7231e';
UPDATE upstream_issues SET disposition = 'test:tests/unit-test-lock-kind.test.mjs' WHERE id = '08b4f5fc-1de9-4a78-8094-25589100b774';
UPDATE upstream_issues SET disposition = 'test:tests/schema-realization.test.mjs' WHERE id = 'bf44711e-81a7-404d-bc0b-33fa68b84903';
UPDATE upstream_issues SET disposition = 'test:tests/schema-realization.test.mjs' WHERE id = '0e61e88e-8294-4144-8bae-84c15db85ea6';
UPDATE upstream_issues SET disposition = 'test:tests/view-writer-key-contract.test.mjs' WHERE id = 'da67a8c1-ec15-4e82-b14d-9b56c983c0a9';
UPDATE upstream_issues SET disposition = 'test:tests/disowned-paths.test.mjs' WHERE id = '5b67666e-0cfe-44d0-b398-a007cd81edad';
UPDATE upstream_issues SET disposition = 'test:tests/view-writer-key-contract.test.mjs' WHERE id = '23544fca-b629-4f15-83d0-dcbcff76f21c';
UPDATE upstream_issues SET disposition = 'probe:sync/orphaned-tooling' WHERE id = '167084b3-97de-4ddc-9526-5da4ef10bfbf';
UPDATE upstream_issues SET disposition = 'test:tests/ship-commit-cli.test.mjs' WHERE id = '575256de-a3ce-48f6-b77a-de061feccf37';
UPDATE upstream_issues SET disposition = 'test:tests/cross-skill-unlocked-scope.test.mjs' WHERE id = '96a829f8-d2b9-457a-b5ab-530b5530dad8';
UPDATE upstream_issues SET disposition = 'exempt:Cosmetic lint fix (an unused eslint-disable comment in a synced file) — no runtime behaviour, no environment signature, and this repo''s test suite does not run ESLint, so no test can regression-lock a lint-only change.' WHERE id = '897aa607-8808-458d-8188-5c1f38caef7f';
UPDATE upstream_issues SET disposition = 'test:tests/ux-lock-capture.test.mjs' WHERE id = 'a0b58a34-5519-4b52-9b07-c9d2c9d56335';
UPDATE upstream_issues SET disposition = 'test:tests/persona-consistency-run-args.test.mjs' WHERE id = 'b5c1860c-8da8-4567-a370-812bd31680d3';
UPDATE upstream_issues SET disposition = 'test:tests/persona-consistency-run-args.test.mjs' WHERE id = '8c62cfcc-ef70-4158-9aed-a00bd232c4ee';
UPDATE upstream_issues SET disposition = 'test:tests/repo-descriptor-callsite-contract.test.mjs' WHERE id = 'd6849e0b-1767-42bc-b4af-b24ed080274b';
UPDATE upstream_issues SET disposition = 'probe:hydration/tooling-absent' WHERE id = 'b5e44db7-c418-4f5e-9791-d53cdf0ee432';

-- Catch-all: any terminal row not covered by the ledger above (closed in the window
-- between this file's generation and its deployment). Caught and closed manually on the
-- next `upstream list --worksheet` via the reconciler, never silently forgotten.
UPDATE upstream_issues SET disposition = 'exempt:legacy-untracked-transition'
  WHERE state IN ('fixed','wont_fix') AND disposition IS NULL;

ALTER TABLE upstream_issues
  DROP CONSTRAINT IF EXISTS chk_upstream_terminal_has_disposition;
ALTER TABLE upstream_issues
  ADD CONSTRAINT chk_upstream_terminal_has_disposition
    CHECK ((state IN ('fixed','wont_fix')) = (disposition IS NOT NULL));

COMMENT ON CONSTRAINT chk_upstream_terminal_has_disposition ON upstream_issues IS
  'Every terminal (fixed|wont_fix) row must carry a disposition, and no non-terminal row may. Enforced at the DB boundary because the CLI-level check in upstreamTransition is necessary but not sufficient — a future second writer must not be able to bypass it.';
