-- upstream_issues.disposition — the closure-disposition ratchet.
--
-- Consumer-friction-doctor plan §2.4: closing an upstream report (fixed |
-- wont_fix) must name EITHER a doctor probe that now detects the failure
-- class (`probe:<id>`), a tracked regression test that closes it
-- (`test:<repo-relative path>`), or a written exemption (`exempt:<reason>`).
-- Before this, closing a report required nothing but a commit sha.
--
-- **Nullable, deliberately, in THIS migration.** 19 historical terminal rows
-- exist and are not yet backfilled when this file runs — a NOT NULL here
-- would break every one of them. The NOT NULL-equivalent invariant
-- (`chk_upstream_terminal_has_disposition`, requiring a disposition on every
-- TERMINAL row) lands in the follow-up migration, GENERATED by
-- `scripts/backfill-upstream-dispositions.mjs` from the reviewed
-- `scripts/upstream-dispositions.json` ledger — literal backfill UPDATEs and
-- the constraint in ONE file, so `setup-postgres.mjs --migrate`'s normal
-- single-transaction-per-file execution guarantees the constraint never
-- exists without the data that satisfies it.
--
-- Shape-checked here (not deferred to the follow-up migration) so a
-- malformed disposition can never even be written, historical backfill aside:
ALTER TABLE upstream_issues
  ADD COLUMN IF NOT EXISTS disposition TEXT;

ALTER TABLE upstream_issues
  DROP CONSTRAINT IF EXISTS chk_upstream_disposition_shape;
ALTER TABLE upstream_issues
  ADD CONSTRAINT chk_upstream_disposition_shape
    CHECK (disposition IS NULL OR disposition ~ '^(probe|test|exempt):.+');

COMMENT ON COLUMN upstream_issues.disposition IS
  'Closure disposition — probe:<doctor-probe-id> | test:<tracked regression test path> | exempt:<reason>. NULL for non-terminal (open|acknowledged) rows. A follow-up migration requires this on every TERMINAL row once the 19 historical rows are backfilled.';
