-- Model-A/B/C experiment harness — persistence + scorer view.
--
-- Plan: docs/plans/model-ab-experiment-harness.md (Cluster B, Phase 4).
-- Generalizes the final-review-shadow attribution (source_model/bucket already
-- on audit_findings from 20260610120000) to the GENERATION passes. Additive +
-- idempotent (ADD COLUMN IF NOT EXISTS / CREATE … IF NOT EXISTS / CREATE OR
-- REPLACE VIEW); no clocks/network → re-runs byte-identically.
--
-- Attribution grain (plan decision 10): a produced finding is stored ONCE with
-- its `stage`; arm membership is DERIVED in the scorer view — NOT an arm_id per
-- finding — so B and C (which share the OSS+GPT execution) never double-count.
-- Provenance: baseline (production A) findings keep stage NULL; the shadow is
-- the ONLY writer of stage ∈ ('oss-gen','gpt-round','gemini').

-- ── 1. audit_findings.stage (the producing generation stage; NOT arm_id) ─────
ALTER TABLE audit_findings ADD COLUMN IF NOT EXISTS stage text;

CREATE INDEX IF NOT EXISTS audit_findings_stage_idx
  ON audit_findings (run_id, stage) WHERE stage IS NOT NULL;

-- ── 2. audit_pass_stats — per-arm-execution usage / cost / conformance ───────
-- input_tokens/output_tokens/latency_ms already exist. Add the arm-execution
-- attribution + cost + structured-output conformance (plan decision 6).
ALTER TABLE audit_pass_stats ADD COLUMN IF NOT EXISTS source_model          text;
ALTER TABLE audit_pass_stats ADD COLUMN IF NOT EXISTS stage                 text;
ALTER TABLE audit_pass_stats ADD COLUMN IF NOT EXISTS structured_output_ok  boolean;
ALTER TABLE audit_pass_stats ADD COLUMN IF NOT EXISTS cost_usd              numeric;
ALTER TABLE audit_pass_stats ADD COLUMN IF NOT EXISTS usage_unmeterable     boolean;

-- New grain is per-arm-execution (plan R2-H3). COALESCE the nullable arm columns
-- so baseline rows (source_model/stage NULL) collapse to one deterministic key
-- and don't create phantom null-duplicates.
CREATE UNIQUE INDEX IF NOT EXISTS audit_pass_stats_arm_grain_uk
  ON audit_pass_stats (
    run_id, pass_name, COALESCE(round, -1),
    COALESCE(source_model, ''), COALESCE(stage, '')
  );

-- ── 3. audit_arms — versioned arm definitions (plan R3-H4) ───────────────────
-- Each audit_run snapshots the arm_set_version it used, so the view's derived
-- membership is stable even if arm configs change mid-experiment.
CREATE TABLE IF NOT EXISTS audit_arms (
  arm_set_version integer     NOT NULL,
  arm_id          text        NOT NULL,
  stages          text[]      NOT NULL,
  is_baseline     boolean     NOT NULL DEFAULT false,
  label           text,
  effective_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (arm_set_version, arm_id)
);

-- Seed arm-set v1 = the canonical A/B/C (mirrors CANONICAL_ARMS in
-- scripts/lib/audit-arms.mjs; the store's ensureArmSet re-asserts this so code
-- stays the source of truth). Idempotent.
INSERT INTO audit_arms (arm_set_version, arm_id, stages, is_baseline, label) VALUES
  (1, 'A', ARRAY['gpt-gen','gemini'],        true,  'GPT ×5 + Gemini gate (production control)'),
  (1, 'B', ARRAY['oss-gen','gpt-round'],     false, 'OSS ×5 + 1 independent GPT round (no Gemini)'),
  (1, 'C', ARRAY['oss-gen','gpt-round','gemini'], false, 'OSS ×5 + 1 GPT round + Gemini gate (reuses B)')
ON CONFLICT (arm_set_version, arm_id) DO NOTHING;

ALTER TABLE audit_runs ADD COLUMN IF NOT EXISTS arm_set_version integer;

-- ── 4. finding_equivalence — durable human cross-model dedup (plan R2-H1) ────
-- The blinded `duplicate` adjudication action writes (duplicate → canonical),
-- collapsed to the ROOT on write (union-find in the store). The disjoint-
-- coverage metric is computed over canonical findings, not raw fingerprints.
CREATE TABLE IF NOT EXISTS finding_equivalence (
  duplicate_finding_id  text        NOT NULL,   -- finding_fingerprint of the dup
  canonical_finding_id  text        NOT NULL,   -- fingerprint of the ROOT
  run_id                uuid,
  created_by            text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (duplicate_finding_id)
);

CREATE INDEX IF NOT EXISTS finding_equivalence_canonical_idx
  ON finding_equivalence (canonical_finding_id);

-- ── 5. model_ab_spend_ledger — reserve-then-reconcile € cap (plan R3-H2) ─────
-- A reservation row is created BEFORE a call (row-locked, atomic across parallel
-- arms); reconciled to actual after `usage` returns. reserved_at + TTL let a
-- reconcile-on-startup release orphaned reservations from a killed run, so a
-- Ctrl-C'd process can't permanently inflate `spent` and block future runs.
CREATE TABLE IF NOT EXISTS model_ab_spend_ledger (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id         uuid,
  arm_id         text,
  stage          text,
  reserved_eur   numeric     NOT NULL,
  actual_eur     numeric,
  estimated      boolean     NOT NULL DEFAULT false,  -- price was a fallback
  unmeterable    boolean     NOT NULL DEFAULT false,  -- usage absent/invalid at reconcile
  status         text        NOT NULL DEFAULT 'reserved',  -- reserved|reconciled|released
  reserved_at    timestamptz NOT NULL DEFAULT now(),
  reconciled_at  timestamptz
);

CREATE INDEX IF NOT EXISTS model_ab_spend_ledger_active_idx
  ON model_ab_spend_ledger (status, reserved_at)
  WHERE status = 'reserved';

-- ── 6. model_ab_effectiveness — the scorer view (arm membership DERIVED) ─────
-- Per (run_id × arm × stage × source_model): accepted / dismissed / pending
-- unique CANONICAL findings (via finding_equivalence) joined to the human
-- adjudication_outcome, plus per-arm-execution cost + conformance from
-- audit_pass_stats. Arm membership derivation (plan decision 10 / 10b):
--   stage NULL             → arm A   (production baseline provenance)
--   stage IN (oss-gen,      → arms B and C  (shadow, compute-shared)
--             gpt-round)
--   stage = gemini         → arm C   (shadow gemini gate — what C adds over B)
-- A finding that is a `duplicate_finding_id` collapses to its canonical, so the
-- disjoint-coverage metric counts issues, not phrasings.
CREATE OR REPLACE VIEW model_ab_effectiveness AS
WITH canon AS (
  SELECT
    f.run_id,
    f.stage,
    f.source_model,
    f.severity,
    COALESCE(f.adjudication_outcome, 'pending') AS outcome,
    COALESCE(fe.canonical_finding_id, f.finding_fingerprint) AS canonical_id,
    CASE
      WHEN f.stage IS NULL                        THEN ARRAY['A']
      WHEN f.stage IN ('oss-gen', 'gpt-round')    THEN ARRAY['B', 'C']
      WHEN f.stage = 'gemini'                     THEN ARRAY['C']
      ELSE ARRAY[]::text[]
    END AS arms
  FROM audit_findings f
  LEFT JOIN finding_equivalence fe
    ON fe.duplicate_finding_id = f.finding_fingerprint
),
expanded AS (
  SELECT run_id, unnest(arms) AS arm, stage, source_model, severity, outcome, canonical_id
  FROM canon
),
pass_cost AS (
  SELECT run_id, stage, source_model,
         SUM(cost_usd)                                   AS cost_usd,
         COUNT(*)                                        AS pass_executions,
         COUNT(*) FILTER (WHERE structured_output_ok)    AS conformant_passes,
         BOOL_OR(usage_unmeterable)                      AS any_unmeterable
  FROM audit_pass_stats
  WHERE stage IS NOT NULL
  GROUP BY run_id, stage, source_model
)
SELECT
  e.run_id,
  e.arm,
  e.stage,
  e.source_model,
  COUNT(DISTINCT e.canonical_id) FILTER (WHERE e.outcome = 'accepted')          AS accepted_uniques,
  COUNT(DISTINCT e.canonical_id) FILTER (WHERE e.outcome = 'dismissed')         AS dismissed_uniques,
  COUNT(DISTINCT e.canonical_id) FILTER (WHERE e.outcome = 'pending')           AS pending_uniques,
  COUNT(DISTINCT e.canonical_id)                                                AS total_uniques,
  COUNT(DISTINCT e.canonical_id) FILTER (WHERE e.severity = 'HIGH' AND e.outcome = 'accepted') AS accepted_high,
  pc.cost_usd,
  pc.pass_executions,
  pc.conformant_passes,
  CASE WHEN pc.pass_executions > 0
       THEN round(pc.conformant_passes::numeric / pc.pass_executions, 4)
       ELSE NULL END                                                            AS conformance_rate,
  pc.any_unmeterable
FROM expanded e
LEFT JOIN pass_cost pc
  ON pc.run_id = e.run_id AND pc.stage = e.stage
     AND COALESCE(pc.source_model, '') = COALESCE(e.source_model, '')
GROUP BY e.run_id, e.arm, e.stage, e.source_model,
         pc.cost_usd, pc.pass_executions, pc.conformant_passes, pc.any_unmeterable;

COMMENT ON VIEW model_ab_effectiveness IS
  'Model-A/B/C scorer: per run × arm × stage × source_model, accepted/dismissed/pending unique CANONICAL findings (via finding_equivalence) joined to human adjudication_outcome, plus per-arm cost + structured-output conformance. Arm membership DERIVED from stage (no per-finding arm_id → no B/C double-count).';
